vault:
  vaultUrl: 'http://vaultUrl'
  rootToken: 'vault root token'

jenkins:
  jenkinsUrl: 'jenkinsUrl'
  jenkinsUsername: 'jenkinsUsername'
  jenkinsPassword: 'jenkinspassword'
  foldername: 'terraform-tests'
  credsId: 'terraform-role-1'
